npm install --save-dev gulp
npm install --save-dev autoprefixer
npm install --save-dev gulp-sass
npm install --save-dev gulp-watch
npm install --save-dev gulp-concat
npm install --save-dev gulp-postcss
npm install --save-dev flexbugs-fixes
npm install --save-dev gulp-clean-css
npm install --save-dev gulp-livereload
npm install --save-dev gulp-uglify
npm install --save-dev gulp-babel
npm install --save-dev gulp-sourcemaps
npm install --save-dev gulp-util